/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltpNative_PostagJNI */

#ifndef _Included_edu_hit_ir_ltpNative_PostagJNI
#define _Included_edu_hit_ir_ltpNative_PostagJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltpNative_PostagJNI
 * Method:    postaggerCreate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_PostagJNI_postaggerCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_hit_ir_ltpNative_PostagJNI
 * Method:    postaggerPostag
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltpNative_PostagJNI_postaggerPostag
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     edu_hit_ir_ltpNative_PostagJNI
 * Method:    postaggerRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_PostagJNI_postaggerRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
