/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltpNative_SegmentJNI */

#ifndef _Included_edu_hit_ir_ltpNative_SegmentJNI
#define _Included_edu_hit_ir_ltpNative_SegmentJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltpNative_SegmentJNI
 * Method:    segmentorCreate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_SegmentJNI_segmentorCreate__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_hit_ir_ltpNative_SegmentJNI
 * Method:    segmentorCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_SegmentJNI_segmentorCreate__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     edu_hit_ir_ltpNative_SegmentJNI
 * Method:    segmentorSegment
 * Signature: (Ljava/lang/String;Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltpNative_SegmentJNI_segmentorSegment
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     edu_hit_ir_ltpNative_SegmentJNI
 * Method:    segmentorRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_SegmentJNI_segmentorRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
