/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltpNative_ParserJNI */

#ifndef _Included_edu_hit_ir_ltpNative_ParserJNI
#define _Included_edu_hit_ir_ltpNative_ParserJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltpNative_ParserJNI
 * Method:    parserCreate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_ParserJNI_parserCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_hit_ir_ltpNative_ParserJNI
 * Method:    parserRarse
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltpNative_ParserJNI_parserRarse
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     edu_hit_ir_ltpNative_ParserJNI
 * Method:    parserRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_ParserJNI_parserRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
