/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltpNative_SplitSentenceJNI */

#ifndef _Included_edu_hit_ir_ltpNative_SplitSentenceJNI
#define _Included_edu_hit_ir_ltpNative_SplitSentenceJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltpNative_SplitSentenceJNI
 * Method:    splitSentence
 * Signature: (Ljava/lang/String;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_SplitSentenceJNI_splitSentence
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
