/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltpNative_NerJNI */

#ifndef _Included_edu_hit_ir_ltpNative_NerJNI
#define _Included_edu_hit_ir_ltpNative_NerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltpNative_NerJNI
 * Method:    nerCreate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltpNative_NerJNI_nerCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_hit_ir_ltpNative_NerJNI
 * Method:    nerRecognize
 * Signature: (Ljava/util/List;Ljava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltpNative_NerJNI_nerRecognize
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     edu_hit_ir_ltpNative_NerJNI
 * Method:    nerRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_NerJNI_nerRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
