/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ir_ltpNative_SrlJNI */

#ifndef _Included_edu_hit_ir_ltpNative_SrlJNI
#define _Included_edu_hit_ir_ltpNative_SrlJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ir_ltpNative_SrlJNI
 * Method:    srlCreate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltpNative_SrlJNI_srlCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_hit_ir_ltpNative_SrlJNI
 * Method:    srlSrl
 * Signature: (Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ir_ltpNative_SrlJNI_srlSrl
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     edu_hit_ir_ltpNative_SrlJNI
 * Method:    srlRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_hit_ir_ltpNative_SrlJNI_srlRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
