/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SrlJNI */

#ifndef _Included_SrlJNI
#define _Included_SrlJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SrlJNI
 * Method:    srlCreate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SrlJNI_srlCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     SrlJNI
 * Method:    srlSrl
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_SrlJNI_srlSrl
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     SrlJNI
 * Method:    srlRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SrlJNI_srlRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
